# Download play data

In [2]:
import pandas as pd

In [3]:
combine_df = pd.read_csv('../../Downloads/combine.csv', on_bad_lines='skip')
combine_df

,year,name,firstname,lastname,position,heightfeet,heightinches,heightinchestotal,weight,arms,...,vertical,broad,bench,round,college,pick,pickround,picktotal,wonderlic,nflgrade
0,2015,Ameer Abdullah,Ameer,Abdullah,RB,5,9.0,69.0,205,0.0,...,42.5,130,24,0,Nebraska,NaN,0,0,0,5.9
1,2015,Nelson Agholor,Nelson,Agholor,WR,6,0.0,72.0,198,0.0,...,0.0,0,12,0,USC,NaN,0,0,0,5.6
2,2015,Jay Ajayi,Jay,Ajayi,RB,6,0.0,72.0,221,0.0,...,39.0,121,19,0,Boise St.,NaN,0,0,0,6.0
3,2015,Kwon Alexander,Kwon,Alexander,OLB,6,1.0,73.0,227,0.0,...,36.0,121,24,0,LSU,NaN,0,0,0,5.4
4,2015,Mario Alford,Mario,Alford,WR,5,8.0,68.0,180,0.0,...,34.0,121,13,0,West Virginia,NaN,0,0,0,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4940,1999,Daren Yancey,Daren,Yancey,DT,6,6.0,78.0,303,0.0,...,26.5,97,0,6,Brigham Young,19(188),19,188,0,0.0
4941,1999,Craig Yeast,Craig,Yeast,WR,5,8.0,68.0,164,0.0,...,32.5,112,0,4,Kentucky,3(98),3,98,0,0.0
4942,1999,Ryan Young,Ryan,Young,OT,6,6.0,78.0,335,0.0,...,0.0,0,20,7,Kansas State,17(223),17,223,0,0.0
4943,1999,Peppi Zellner,Peppi,Zellner,DE,6,5.0,77.0,246,0.0,...,35.5,122,20,4,Fort Valley State,37(132),37,132,0,0.0
4944,1999,Amos Zereoue,Amos,Zereoue,RB,5,8.0,68.0,203,0.0,...,0.0,0,0,3,West Virginia,34(95),34,95,0,0.0

In [4]:
play_df = pd.read_csv('../../Downloads/archive-2/NFL Play by Play 2009-2018 (v5).csv', on_bad_lines='skip')
play_df

/var/folders/gs/8tgf4cmn2351ctdnwfbqr2480000gn/T/ipykernel_1178/739972372.py:1: DtypeWarning: Columns (42,166,167,168,169,174,175,178,179,182,183,188,189,190,191,194,195,203,204,205,218,219,220,231,232,233,238,240,241,249) have mixed types. Specify dtype option on import or set low_memory=False.
  play_df = pd.read_csv('../../Downloads/archive-2/NFL Play by Play 2009-2018 (v5).csv', on_bad_lines='skip')

,play_id,game_id,home_team,away_team,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date,...,penalty_player_id,penalty_player_name,penalty_yards,replay_or_challenge,replay_or_challenge_result,penalty_type,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv
0,46,2009091000,PIT,TEN,PIT,home,TEN,TEN,30.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
1,68,2009091000,PIT,TEN,PIT,home,TEN,PIT,58.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
2,92,2009091000,PIT,TEN,PIT,home,TEN,PIT,53.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
3,113,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
4,139,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449366,4059,2018121700,CAR,NO,CAR,home,NO,CAR,66.0,2018-12-17,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
449367,4081,2018121700,CAR,NO,CAR,home,NO,CAR,66.0,2018-12-17,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
449368,4106,2018121700,CAR,NO,CAR,home,NO,CAR,61.0,2018-12-17,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
449369,4128,2018121700,CAR,NO,NO,away,CAR,CAR,39.0,2018-12-17,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
449370,4150,2018121700,CAR,NO,NaN,NaN,NaN,CAR,NaN,2018-12-17,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
players_df = pd.read_csv('../../Downloads/players_2013-12-12.csv', on_bad_lines='skip')
players_df

,name,first_name,last_name,birth_city,birth_state,birth_country,birth_date,college,draft_team,draft_round,...,draft_year,position,height,weight,death_date,death_city,death_state,death_country,year_start,year_end
0,Isaako Aaitui,Isaako,Aaitui,NaN,NaN,NaN,1/25/1987,NaN,NaN,NaN,...,NaN,NT,4-Jun,315.0,NaN,NaN,NaN,NaN,2013,2013
1,Faye Abbott,Faye,Abbott,Clearport,OH,USA,1895-08-16,Syracuse,NaN,NaN,...,NaN,BB-FB-TB-QB-WB-,8-May,182.0,1/22/1965,Dayton,OH,NaN,1921,1929
2,Vince Abbott,Vince,Abbott,London,NaN,England,5/31/1958,Washington,NaN,NaN,...,NaN,K,11-May,207.0,NaN,NaN,NaN,NaN,1921,1929
3,Duke Abbruzzi,Duke,Abbruzzi,Warren,RI,USA,8/3/1917,Rhode Island,NaN,NaN,...,NaN,HB-DB,10-May,175.0,12/6/1982,Newport,RI,NaN,1921,1929
4,Karim Abdul-Jabbar,Karim,Abdul-Jabbar,Los Angeles,CA,USA,6/28/1974,UCLA,Miami Dolphins,3rd,...,1996.0,RB,10-May,194.0,NaN,NaN,NaN,NaN,1996,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23728,Markus Zusevics,Markus,Zusevics,NaN,NaN,NaN,4/25/1989,Iowa,NaN,NaN,...,NaN,OL,5-Jun,300.0,NaN,NaN,NaN,NaN,2012,2013
23729,Jeremy Zuttah,Jeremy,Zuttah,Edison,NJ,USA,6/1/1986,Rutgers,Tampa Bay Buccaneers,3rd,...,2008.0,G,4-Jun,303.0,NaN,NaN,NaN,NaN,2008,2013
23730,Merle Zuver,Merle,Zuver,Adams,NE,USA,1/25/1905,Nebraska,NaN,NaN,...,NaN,G-C,1-Jun,198.0,3/25/1969,Phoenix,AZ,NaN,1930,1930
23731,Tony Zuzzio,Tony,Zuzzio,Irvington,NJ,USA,8/5/1916,Muhlenberg,NaN,NaN,...,NaN,G,11-May,210.0,4/7/2002,Lawrence,KS,NaN,1942,1942
23732,Jim Zyntell,Jim,Zyntell,Boston,MA,USA,4/27/1910,Holy Cross,NaN,NaN,...,NaN,G,1-Jun,200.0,NaN,NaN,NaN,NaN,1933,1935

In [8]:
# players_df.types
players_df.columns

Index(['name', 'first_name', 'last_name', 'birth_city', 'birth_state',
       'birth_country', 'birth_date', 'college', 'draft_team', 'draft_round',
       'draft_pick', 'draft_year', 'position', 'height', 'weight',
       'death_date', 'death_city', 'death_state', 'death_country',
       'year_start', 'year_end'],
      dtype='object')

In [9]:
weather_df = pd.read_csv('../../Downloads/weather_20131231.csv', on_bad_lines='skip')
weather_df

,id,home_team,home_score,away_team,away_score,temperature,wind_chill,humidity,wind_mph,weather,date
0,196009230ram,Los Angeles Rams,21,St. Louis Cardinals,43,66,NaN,78%,8.0,66 degrees- relative humidity 78%- wind 8 mph,9/23/1960
1,196009240dal,Dallas Cowboys,28,Pittsburgh Steelers,35,72,NaN,80%,16.0,72 degrees- relative humidity 80%- wind 16 mph,9/24/1960
2,196009250gnb,Green Bay Packers,14,Chicago Bears,17,60,NaN,76%,13.0,60 degrees- relative humidity 76%- wind 13 mph,9/25/1960
3,196009250sfo,San Francisco 49ers,19,New York Giants,21,72,NaN,44%,10.0,72 degrees- relative humidity 44%- wind 10 mph,9/25/1960
4,196009250clt,Baltimore Colts,20,Washington Redskins,0,62,NaN,80%,9.0,62 degrees- relative humidity 80%- wind 9 mph,9/25/1960
...,...,...,...,...,...,...,...,...,...,...,...
11187,201312290nwe,New England Patriots,34,Buffalo Bills,20,39,NaN,100%,8.0,39 degrees- relative humidity 100%- wind 8 mph,12/29/2013
11188,201312290atl,Atlanta Falcons,20,Carolina Panthers,21,0,0.0,NaN,NaN,0 degrees- no wind- wind chill 0,12/29/2013
11189,201312290pit,Pittsburgh Steelers,20,Cleveland Browns,7,40,NaN,93%,5.0,40 degrees- relative humidity 93%- wind 5 mph,12/29/2013
11190,201312290rai,Oakland Raiders,14,Denver Broncos,34,70,0.0,16%,8.0,70 degrees- relative humidity 16%- wind 8 mph-...,12/29/2013
11191,201312290mia,Miami Dolphins,7,New York Jets,20,79,0.0,84%,12.0,79 degrees- relative humidity 84%- wind 12 mph...,12/29/2013

In [10]:
passing_df = pd.read_csv('../../Downloads/passing_cleaned.csv', on_bad_lines='skip')
passing_df

,Unnamed: 0,Player,Tm,Age,G,GS,Cmp,Att,Cmp%,Yds,...,AY/A,Y/C,Y/G,Rate,Sk,Yds-s,Sk%,NY/A,ANY/A,Year
0,0,Kurt Warner,STL,30,16,16,375,546,68.7,4830,...,8.4,12.9,301.9,101.4,38,233,6.5,7.87,7.41,2001
1,1,Peyton Manning,IND,25,16,16,343,547,62.7,4131,...,6.6,12.0,258.2,84.1,29,232,5.0,6.77,5.88,2001
2,2,Brett Favre,GNB,32,16,16,314,510,61.6,3921,...,7.6,12.5,245.1,94.1,22,151,4.1,7.09,7.02,2001
3,3,Aaron Brooks,NOR,25,16,16,312,558,55.9,3832,...,6.0,12.3,239.5,76.4,50,330,8.2,5.76,4.99,2001
4,4,Rich Gannon,OAK,36,16,16,361,549,65.8,3828,...,7.2,10.6,239.3,95.5,27,155,4.7,6.38,6.61,2001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2345,2389,Kadarius Toney,KAN,24,13,2,0,1,0.0,0,...,0.0,0.0,0.0,39.6,0,0,0.0,0.00,0.00,2023
2346,2390,Kyle Trask,TAM,25,2,0,0,1,0.0,0,...,0.0,0.0,0.0,39.6,0,0,0.0,0.00,0.00,2023
2347,2391,Garrett Wilson,NYJ,23,17,17,0,1,0.0,0,...,0.0,0.0,0.0,39.6,0,0,0.0,0.00,0.00,2023
2348,2392,Christian Kirk,JAX,27,12,12,1,2,50.0,-1,...,-0.5,-1.0,-0.1,56.2,0,0,0.0,-0.50,-0.50,2023
2349,2393,Ja'Marr Chase,CIN,23,16,16,1,1,100.0,-7,...,-7.0,-7.0,-0.4,79.2,0,0,0.0,-7.00,-7.00,2023

In [17]:
# passing_df.columns
passing_df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2350 entries, 0 to 2349
Data columns (total 27 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2350 non-null   int64
 1   Player      2350 non-null   object
 2   Tm          2350 non-null   object
 3   Age         2350 non-null   int64
 4   G           2350 non-null   int64
 5   GS          2350 non-null   int64
 6   Cmp         2350 non-null   int64
 7   Att         2350 non-null   int64
 8   Cmp%        2350 non-null   float64
 9   Yds         2350 non-null   int64
 10  TD          2350 non-null   int64
 11  TD%         2350 non-null   float64
 12  Int         2350 non-null   int64
 13  Int%        2350 non-null   float64
 14  1D          2350 non-null   int64
 15  Lng         2350 non-null   int64
 16  Y/A         2350 non-null   float64
 17  AY/A        2350 non-null   float64
 18  Y/C         2350 non-null   float64
 19  Y/G         2350 non-null   float64
 20  Rate        2350 non-null   float64
 21  Sk          2350 non-null   int64
 22  Yds-s       2350 non-null   int64
 23  Sk%         2350 non-null   float64
 24  NY/A        2350 non-null   float64
 25  ANY/A       2350 non-null   float64
 26  Year        2350 non-null   int64
dtypes: float64(11), int64(14), object(2)
memory usage: 495.8+ KB

In [20]:
players_df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23733 entries, 0 to 23732
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           23733 non-null  object
 1   first_name     23706 non-null  object
 2   last_name      23733 non-null  object
 3   birth_city     20932 non-null  object
 4   birth_state    20683 non-null  object
 5   birth_country  21114 non-null  object
 6   birth_date     23384 non-null  object
 7   college        23492 non-null  object
 8   draft_team     14215 non-null  object
 9   draft_round    14215 non-null  object
 10  draft_pick     14215 non-null  object
 11  draft_year     14215 non-null  float64
 12  position       23731 non-null  object
 13  height         23416 non-null  object
 14  weight         23558 non-null  float64
 15  death_date     4525 non-null   object
 16  death_city     4396 non-null   object
 17  death_state    4416 non-null   object
 18  death_country  13 non-null     object
 19  year_start     23733 non-null  int64
 20  year_end       23733 non-null  int64
dtypes: float64(2), int64(2), object(17)
memory usage: 3.8+ MB

In [16]:
play_df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 449371 entries, 0 to 449370
Data columns (total 255 columns):
 #    Column                                Dtype
---   ------                                -----
 0    play_id                               int64
 1    game_id                               int64
 2    home_team                             object
 3    away_team                             object
 4    posteam                               object
 5    posteam_type                          object
 6    defteam                               object
 7    side_of_field                         object
 8    yardline_100                          float64
 9    game_date                             object
 10   quarter_seconds_remaining             float64
 11   half_seconds_remaining                float64
 12   game_seconds_remaining                float64
 13   game_half                             object
 14   quarter_end                           int64
 15   drive                                 int64
 16   sp                                    int64
 17   qtr                                   int64
 18   down                                  float64
 19   goal_to_go                            float64
 20   time                                  object
 21   yrdln                                 object
 22   ydstogo                               int64
 23   ydsnet                                int64
 24   desc                                  object
 25   play_type                             object
 26   yards_gained                          float64
 27   shotgun                               int64
 28   no_huddle                             int64
 29   qb_dropback                           float64
 30   qb_kneel                              int64
 31   qb_spike                              int64
 32   qb_scramble                           int64
 33   pass_length                           object
 34   pass_location                         object
 35   air_yards                             float64
 36   yards_after_catch                     float64
 37   run_location                          object
 38   run_gap                               object
 39   field_goal_result                     object
 40   kick_distance                         float64
 41   extra_point_result                    object
 42   two_point_conv_result                 object
 43   home_timeouts_remaining               int64
 44   away_timeouts_remaining               int64
 45   timeout                               float64
 46   timeout_team                          object
 47   td_team                               object
 48   posteam_timeouts_remaining            float64
 49   defteam_timeouts_remaining            float64
 50   total_home_score                      int64
 51   total_away_score                      int64
 52   posteam_score                         float64
 53   defteam_score                         float64
 54   score_differential                    float64
 55   posteam_score_post                    float64
 56   defteam_score_post                    float64
 57   score_differential_post               float64
 58   no_score_prob                         float64
 59   opp_fg_prob                           float64
 60   opp_safety_prob                       float64
 61   opp_td_prob                           float64
 62   fg_prob                               float64
 63   safety_prob                           float64
 64   td_prob                               float64
 65   extra_point_prob                      float64
 66   two_point_conversion_prob             float64
 67   ep                                    float64
 68   epa                                   float64
 69   total_home_epa                        float64
 70   total_away_epa                        float64
 71   total_home_rush_epa                   float64
 72   total_away_rush_epa                   float64
 73   total_home_pass_epa                   float64
 74   total_away_pass_epa                   float64
 75   air_epa                               float64
 76   yac_epa                               float64
 77   comp_air_epa                          float64
 78   comp_yac_epa                          float64
 79   total_home_comp_air_epa               float64
 80   total_away_comp_air_epa               float64
 81   total_home_comp_yac_epa               float64
 82   total_away_comp_yac_epa               float64
 83   total_home_raw_air_epa                float64
 84   total_away_raw_air_epa                float64
 85   total_home_raw_yac_epa                float64
 86   total_away_raw_yac_epa                float64
 87   wp                                    float64
 88   def_wp                                float64
 89   home_wp                               float64
 90   away_wp                               float64
 91   wpa                                   float64
 92   home_wp_post                          float64
 93   away_wp_post                          float64
 94   total_home_rush_wpa                   float64
 95   total_away_rush_wpa                   float64
 96   total_home_pass_wpa                   float64
 97   total_away_pass_wpa                   float64
 98   air_wpa                               float64
 99   yac_wpa                               float64
 100  comp_air_wpa                          float64
 101  comp_yac_wpa                          float64
 102  total_home_comp_air_wpa               float64
 103  total_away_comp_air_wpa               float64
 104  total_home_comp_yac_wpa               float64
 105  total_away_comp_yac_wpa               float64
 106  total_home_raw_air_wpa                float64
 107  total_away_raw_air_wpa                float64
 108  total_home_raw_yac_wpa                float64
 109  total_away_raw_yac_wpa                float64
 110  punt_blocked                          float64
 111  first_down_rush                       float64
 112  first_down_pass                       float64
 113  first_down_penalty                    float64
 114  third_down_converted                  float64
 115  third_down_failed                     float64
 116  fourth_down_converted                 float64
 117  fourth_down_failed                    float64
 118  incomplete_pass                       float64
 119  interception                          float64
 120  punt_inside_twenty                    float64
 121  punt_in_endzone                       float64
 122  punt_out_of_bounds                    float64
 123  punt_downed                           float64
 124  punt_fair_catch                       float64
 125  kickoff_inside_twenty                 float64
 126  kickoff_in_endzone                    float64
 127  kickoff_out_of_bounds                 float64
 128  kickoff_downed                        float64
 129  kickoff_fair_catch                    float64
 130  fumble_forced                         float64
 131  fumble_not_forced                     float64
 132  fumble_out_of_bounds                  float64
 133  solo_tackle                           float64
 134  safety                                float64
 135  penalty                               float64
 136  tackled_for_loss                      float64
 137  fumble_lost                           float64
 138  own_kickoff_recovery                  float64
 139  own_kickoff_recovery_td               float64
 140  qb_hit                                float64
 141  rush_attempt                          float64
 142  pass_attempt                          float64
 143  sack                                  float64
 144  touchdown                             float64
 145  pass_touchdown                        float64
 146  rush_touchdown                        float64
 147  return_touchdown                      float64
 148  extra_point_attempt                   float64
 149  two_point_attempt                     float64
 150  field_goal_attempt                    float64
 151  kickoff_attempt                       float64
 152  punt_attempt                          float64
 153  fumble                                float64
 154  complete_pass                         float64
 155  assist_tackle                         float64
 156  lateral_reception                     float64
 157  lateral_rush                          float64
 158  lateral_return                        float64
 159  lateral_recovery                      float64
 160  passer_player_id                      object
 161  passer_player_name                    object
 162  receiver_player_id                    object
 163  receiver_player_name                  object
 164  rusher_player_id                      object
 165  rusher_player_name                    object
 166  lateral_receiver_player_id            object
 167  lateral_receiver_player_name          object
 168  lateral_rusher_player_id              object
 169  lateral_rusher_player_name            object
 170  lateral_sack_player_id                float64
 171  lateral_sack_player_name              float64
 172  interception_player_id                object
 173  interception_player_name              object
 174  lateral_interception_player_id        object
 175  lateral_interception_player_name      object
 176  punt_returner_player_id               object
 177  punt_returner_player_name             object
 178  lateral_punt_returner_player_id       object
 179  lateral_punt_returner_player_name     object
 180  kickoff_returner_player_name          object
 181  kickoff_returner_player_id            object
 182  lateral_kickoff_returner_player_id    object
 183  lateral_kickoff_returner_player_name  object
 184  punter_player_id                      object
 185  punter_player_name                    object
 186  kicker_player_name                    object
 187  kicker_player_id                      object
 188  own_kickoff_recovery_player_id        object
 189  own_kickoff_recovery_player_name      object
 190  blocked_player_id                     object
 191  blocked_player_name                   object
 192  tackle_for_loss_1_player_id           object
 193  tackle_for_loss_1_player_name         object
 194  tackle_for_loss_2_player_id           object
 195  tackle_for_loss_2_player_name         object
 196  qb_hit_1_player_id                    object
 197  qb_hit_1_player_name                  object
 198  qb_hit_2_player_id                    object
 199  qb_hit_2_player_name                  object
 200  forced_fumble_player_1_team           object
 201  forced_fumble_player_1_player_id      object
 202  forced_fumble_player_1_player_name    object
 203  forced_fumble_player_2_team           object
 204  forced_fumble_player_2_player_id      object
 205  forced_fumble_player_2_player_name    object
 206  solo_tackle_1_team                    object
 207  solo_tackle_2_team                    object
 208  solo_tackle_1_player_id               object
 209  solo_tackle_2_player_id               object
 210  solo_tackle_1_player_name             object
 211  solo_tackle_2_player_name             object
 212  assist_tackle_1_player_id             object
 213  assist_tackle_1_player_name           object
 214  assist_tackle_1_team                  object
 215  assist_tackle_2_player_id             object
 216  assist_tackle_2_player_name           object
 217  assist_tackle_2_team                  object
 218  assist_tackle_3_player_id             object
 219  assist_tackle_3_player_name           object
 220  assist_tackle_3_team                  object
 221  assist_tackle_4_player_id             float64
 222  assist_tackle_4_player_name           float64
 223  assist_tackle_4_team                  float64
 224  pass_defense_1_player_id              object
 225  pass_defense_1_player_name            object
 226  pass_defense_2_player_id              object
 227  pass_defense_2_player_name            object
 228  fumbled_1_team                        object
 229  fumbled_1_player_id                   object
 230  fumbled_1_player_name                 object
 231  fumbled_2_player_id                   object
 232  fumbled_2_player_name                 object
 233  fumbled_2_team                        object
 234  fumble_recovery_1_team                object
 235  fumble_recovery_1_yards               float64
 236  fumble_recovery_1_player_id           object
 237  fumble_recovery_1_player_name         object
 238  fumble_recovery_2_team                object
 239  fumble_recovery_2_yards               float64
 240  fumble_recovery_2_player_id           object
 241  fumble_recovery_2_player_name         object
 242  return_team                           object
 243  return_yards                          float64
 244  penalty_team                          object
 245  penalty_player_id                     object
 246  penalty_player_name                   object
 247  penalty_yards                         float64
 248  replay_or_challenge                   int64
 249  replay_or_challenge_result            object
 250  penalty_type                          object
 251  defensive_two_point_attempt           float64
 252  defensive_two_point_conv              float64
 253  defensive_extra_point_attempt         float64
 254  defensive_extra_point_conv            float64
dtypes: float64(135), int64(18), object(102)
memory usage: 874.2+ MB

In [18]:
combine_df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4945 entries, 0 to 4944
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   year               4945 non-null   int64
 1   name               4945 non-null   object
 2   firstname          4945 non-null   object
 3   lastname           4945 non-null   object
 4   position           4945 non-null   object
 5   heightfeet         4945 non-null   int64
 6   heightinches       4945 non-null   float64
 7   heightinchestotal  4945 non-null   float64
 8   weight             4945 non-null   int64
 9   arms               4945 non-null   float64
 10  hands              4945 non-null   float64
 11  fortyyd            4945 non-null   float64
 12  twentyyd           4945 non-null   float64
 13  tenyd              4945 non-null   float64
 14  twentyss           4945 non-null   float64
 15  threecone          4945 non-null   float64
 16  vertical           4945 non-null   float64
 17  broad              4945 non-null   int64
 18  bench              4945 non-null   int64
 19  round              4945 non-null   int64
 20  college            3475 non-null   object
 21  pick               3156 non-null   object
 22  pickround          4945 non-null   int64
 23  picktotal          4945 non-null   int64
 24  wonderlic          4945 non-null   int64
 25  nflgrade           4945 non-null   float64
dtypes: float64(11), int64(9), object(6)
memory usage: 1004.6+ KB

In [22]:
weather_df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11192 entries, 0 to 11191
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           11192 non-null  object
 1   home_team    11192 non-null  object
 2   home_score   11192 non-null  int64
 3   away_team    11192 non-null  object
 4   away_score   11192 non-null  int64
 5   temperature  11192 non-null  int64
 6   wind_chill   1617 non-null   float64
 7   humidity     9285 non-null   object
 8   wind_mph     9347 non-null   float64
 9   weather      11192 non-null  object
 10  date         11192 non-null  object
dtypes: float64(2), int64(3), object(6)
memory usage: 961.9+ KB

In [26]:
# plot every column in weather_df and save to file
import matplotlib.pyplot as plt
import seaborn as sns
import os
import numpy as np

def plot_weather(df, column):   
    plt.figure(figsize=(10, 6))
    sns.histplot(df[column], bins=30, kde=True)
    plt.title(f'Distribution of {column}')
    plt.xlabel(column)
    plt.ylabel('Frequency')
    plt.grid()
    plt.savefig(f'weather_columns/weather_{column}.png')
    plt.close()

Matplotlib is building the font cache; this may take a moment.

In [ ]:
# Create a directory to save the plots
if not os.path.exists('weather_columns'):
    os.makedirs('weather_columns')
for column in weather_df.columns:
    plot_weather(weather_df, column)

Plotted id
Plotted home_team
Plotted home_score
Plotted away_team
Plotted away_score
Plotted temperature
Plotted wind_chill
Plotted humidity
Plotted wind_mph
Plotted weather
Plotted date